### ISSUE TITLE
Matching dark theme

### ISSUE THREAD

**Issue by controversial** [sindresorhus/alfred-simple#2]
Have you considered releasing a similar dark theme? I really like the look of `alfred-simple` but it'd look better in macOS dark mode if it were dark. Spotlight automatically turns dark when dark mode is enabled, but I doubt Alfred themes are offered this flexibility.

**Comment by uschek** [comment]
@controversial I just created [alfred-simple-dark](https://github.com/uschek/alfred-simple-dark).

**Comment by sindresorhus** [comment]
Done now.
